apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtlamr2mqtt
  namespace: home-automation
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rtlamr2mqtt
  template:
    metadata:
      labels:
        app: rtlamr2mqtt
    spec:
      enableServiceLinks: false
      containers:
        - name: main
          image: forge.internal/nemo/rtlamr2mqtt:6d60a6e-1774025524
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: config-file
              mountPath: /etc/rtlamr2mqtt.yaml
              subPath: rtlamr2mqtt.yaml
              readOnly: true
      volumes:
        - name: config-file
          secret:
            secretName: rtlamr2mqtt-config
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "rtlsdr.feature.node.kubernetes.io/v3"
                    operator: "In"
                    values:
                      - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: "In"
                    values:
                      - "rtl433"
