---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ca-configmap.yaml
  # Note: PVC is managed by volsync-v2 component
components:
  - ../../../components/volsync-v2
