---
apiVersion: v1
kind: Namespace
metadata:
  name: volume-freezer
  labels:
    kubernetes.io/metadata.name: volume-freezer
    # Freezer needs privileged mode to nsenter into target containers
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
