name: Bump flake.lock

on:
  schedule:
    # Starting at midnight (4am UTC)
    - cron: "0 4 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: native
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31

      - run: nix flake update

      - name: Commit and push changes
        run: |
          git config --local user.email "flakebot@ptinem.casa"
          git config --local user.name "Flake Bot"
          git add flake.lock
          git diff --quiet && git diff --staged --quiet || (
            git commit --no-verify --signoff -m "Bump flake.lock"
            git push
          )
