name: Bump flake.lock

on:
  schedule:
    # Starting at midnight (4am UTC)
    - cron: "0 4 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: native
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check git config after checkout
        shell: bash
        run: |
          echo "=== Git config ==="
          git config --list | grep -E "(http|credential|core\.sshCommand)" || echo "No http/credential configs found"
          echo "=== Git remote ==="
          git remote -v
          echo "=== GIT_* environment variables ==="
          env | grep "^GIT_" || echo "No GIT_* vars"
          echo "=== HOME and credentials files ==="
          ls -la ~/ | grep -E "(\.git|credential)" || echo "No .git* or credential files"

      - run: |
          nix flake update

      - name: Git Push Simulation (dry-run)
        shell: bash
        timeout-minutes: 5
        run: |
          echo "=== Current git status ==="
          git status
          echo "=== Testing git push dry-run (60 sec timeout) ==="
          timeout 60 git push --dry-run --verbose origin main 2>&1 || echo "Push simulation timed out or failed with exit code: $?"

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Bump flake.lock
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot
          commit_user_email: flakebot@ptinem.casa
          commit_author: Flake Bot <flakebot@ptinem.casa>
          skip_dirty_check: false
          skip_fetch: true
