name: Test Docker Runner

on:
  workflow_dispatch:

jobs:
  # Test 1: Native runner (baseline - should work)
  test-native:
    runs-on: native
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: List files
        run: ls -la

      - name: Show environment
        run: |
          echo "PWD: $PWD"
          echo "USER: $USER"
          echo "HOME: $HOME"
          uname -a

  # Test 2: Docker runner (simple test - might fail)
  test-docker-simple:
    runs-on: docker
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: List files
        run: ls -la

      - name: Show environment
        run: |
          echo "PWD: $PWD"
          echo "USER: $USER"
          echo "HOME: $HOME"
          uname -a

  # Test 3: Docker runner with Docker actions (like bitwarden-cli)
  test-docker-with-docker-actions:
    runs-on: docker
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: /etc/buildkit/buildkitd.toml

      - name: Verify setup
        run: |
          echo "Docker Buildx setup completed"
          docker version || echo "Docker not available"
          docker buildx version || echo "Buildx not available"
