{ config, lib, pkgs, imports, modulesPath, ... }:

with lib;
{
  # NOTE
  # Some 'global' areas have defaults set in their respective modules.
  # These will be applied when the modules are loaded
  # Not the global role.
  # Not sure at this point a good way to manage globals in one place
  # without mono-repo config.

  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix") # Generated by nixos-config-generate
      ./global
    ];

  config = {

    # delete all files in /tmp during boot.
    boot.tmp.cleanOnBoot = true;

    # CVE-2026-31431 ("Copy Fail") — algif_aead LPE. Mitigation until the
    # 6.12.85+ backport reaches nixpkgs. AF_ALG AEAD has no consumers here.
    boot.blacklistedKernelModules = [ "algif_aead" ];

    # use DHCP to obtain an IP address
    networking.useDHCP = lib.mkDefault true;

    time.timeZone = "America/New_York";

    environment.systemPackages = with pkgs; [
      fastfetch
      vim
      helix
    ];

    ## TODO see where to place those
    # Ensure ssh is up
    services.sshd.enable = true;

    # NTP time sync
    services.timesyncd.enable = lib.mkDefault true;

    security.sudo = {
      enable = true;
      wheelNeedsPassword = false;
    };
    ## END TODO

    # Use the Python rewrite of nixos-rebuild. Fixes list-generations showing
    # "Unknown" kernel versions (bash version looks in the wrong store path).
    system.rebuild.enableNg = true;

    mySystem.services.logging.enable = true;
  };

}