apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ca-configmap.yaml
  - oidc-external-secret.yaml
  - matrix-external-secret.yaml
  - claude-external-secret.yaml
