apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      nodeSelector:
        zigbee.feature.node.kubernetes.io/sonoff: "true"
      securityContext:
        supplementalGroups:
          - 27
      containers:
      - name: zigbee2mqtt
        image: ghcr.io/koenkk/zigbee2mqtt:latest
        securityContext:
          privileged: true
        env:
        - name: ZIGBEE2MQTT_DATA
          value: /app/data
        - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED
          value: "true"
        - name: ZIGBEE2MQTT_CONFIG_PERMIT_JOIN
          value: "true"
        - name: ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC
          value: zigbee2mqtt
        - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
          value: mqtt://mqtt.internal
        - name: ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER
          value: zstack
        - name: ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED
          value: "true"
        - name: ZIGBEE2MQTT_CONFIG_FRONTEND_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: device
          mountPath: /dev/ttyUSB0
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zigbee2mqtt
      - name: device
        hostPath:
          path: /dev/ttyUSB0
          type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  selector:
    app: zigbee2mqtt
  ports:
  - port: 80
    targetPort: 8080
    name: http
