apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-pvc
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
