---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-appservice-secondbrain
  namespace: self-hosted
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: synapse-appservice-secondbrain
    creationPolicy: Owner
  data:
    - secretKey: AS_TOKEN
      remoteRef:
        key: f0c7bc37-4f9d-4801-b1df-7af590dabc08
        property: as_token
    - secretKey: HS_TOKEN
      remoteRef:
        key: f0c7bc37-4f9d-4801-b1df-7af590dabc08
        property: hs_token
