---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-oidc
  namespace: self-hosted
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: synapse-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: 4b07c753-4773-4ff0-9fea-8fc18768958c
        property: client_id
    - secretKey: client-secret
      remoteRef:
        key: 4b07c753-4773-4ff0-9fea-8fc18768958c
        property: client_secret
