---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-secrets
  namespace: self-hosted
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: synapse-secrets
    creationPolicy: Owner
  data:
    - secretKey: REGISTRATION_SECRET
      remoteRef:
        key: c912e505-f756-4c41-8e9f-69e332c0ff9c
        property: REGISTRATION_SECRET
    - secretKey: SIGNING_KEY
      remoteRef:
        key: c912e505-f756-4c41-8e9f-69e332c0ff9c
        property: SIGNING_KEY
