#!/usr/bin/env bash
set -euo pipefail

# PRD Runner — executes a single PRD file autonomously
# Usage: prd-runner.sh <prd-file>

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LOG_DIR="${ROOT_DIR}/logs/prd"
mkdir -p "$LOG_DIR"

prd_file="$1"
if [[ ! -f "$prd_file" ]]; then
  echo "ERROR: PRD file not found: $prd_file"
  exit 1
fi

# Parse frontmatter with yq (extract YAML between --- delimiters)
frontmatter() {
  sed -n '/^---$/,/^---$/p' "$prd_file" | sed '1d;$d' | yq eval "$1" -
}

prd_id="$(frontmatter '.id')"
prd_title="$(frontmatter '.title')"
prd_branch="$(frontmatter '.branch')"
prd_status="$(frontmatter '.status')"
log_file="${LOG_DIR}/${prd_id}-$(date +%Y%m%d-%H%M%S).log"

log() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$log_file"; }

log "PRD ${prd_id}: ${prd_title}"
log "Branch: ${prd_branch}"
log "Status: ${prd_status}"

# Check status
if [[ "$prd_status" != "pending" ]]; then
  log "Skipping — status is '${prd_status}', not 'pending'"
  exit 0
fi

# Check dependencies
dep_count="$(frontmatter '.depends_on | length')"
if [[ "$dep_count" -gt 0 ]]; then
  for i in $(seq 0 $((dep_count - 1))); do
    dep_id="$(frontmatter ".depends_on[$i]")"
    dep_file="$(find "${ROOT_DIR}/docs/prd" -name "${dep_id}-*.md" | head -1)"
    if [[ -z "$dep_file" ]]; then
      log "ERROR: Dependency ${dep_id} not found"
      exit 1
    fi
    dep_status="$(sed -n '/^---$/,/^---$/p' "$dep_file" | sed '1d;$d' | yq eval '.status' -)"
    if [[ "$dep_status" != "passed" ]]; then
      log "Skipping — dependency ${dep_id} has status '${dep_status}'"
      exit 0
    fi
  done
fi

# Set status to running
set_status() {
  local new_status="$1"
  sed -i "s/^status: .*/status: ${new_status}/" "$prd_file"
}
set_status "running"

cleanup() {
  cd "$ROOT_DIR"
  git checkout main 2>/dev/null || true
}
trap cleanup EXIT

# Create branch
log "Creating branch ${prd_branch} from main"
cd "$ROOT_DIR"
git checkout main
git pull --ff-only || true
git checkout -b "$prd_branch"

# Invoke Claude Code
log "Invoking Claude Code..."
SAFETY_PROMPT="You are executing an autonomous PRD task. Rules:
- Do NOT modify files in secrets/, .sops.yaml, .envrc, or age keys
- Do NOT run kubectl, argocd, ssh, or sops commands
- Do NOT delete files unless the PRD explicitly requires it
- Do NOT modify files outside the scope defined in the PRD
- Work from the repository root: ${ROOT_DIR}
- Make all changes needed to satisfy the requirements below."

prd_content="$(cat "$prd_file")"

claude --print \
  --model sonnet \
  --allowedTools "Edit,Write,Read,Glob,Grep,Bash(git *),Bash(just lint),Bash(just format),Bash(kustomize *),Bash(nix build *),Bash(nix flake check),Bash(ls *),Bash(mkdir *)" \
  --append-system-prompt "$SAFETY_PROMPT" \
  "$prd_content" \
  >> "$log_file" 2>&1

# Post-run safety check — abort if forbidden files were modified
log "Running safety checks..."
forbidden_pattern='(^secrets/|\.sops\.yaml$|\.envrc$|age\.key)'
if git diff --name-only main | grep -qE "$forbidden_pattern"; then
  log "SAFETY VIOLATION: Forbidden files were modified:"
  git diff --name-only main | grep -E "$forbidden_pattern" | tee -a "$log_file"
  git checkout main
  git branch -D "$prd_branch" 2>/dev/null || true
  set_status "failed"
  exit 1
fi

# Run verification commands
log "Running verification commands..."
verify_count="$(frontmatter '.verify | length')"
verify_failed=0

for i in $(seq 0 $((verify_count - 1))); do
  verify_cmd="$(frontmatter ".verify[$i].cmd")"
  verify_desc="$(frontmatter ".verify[$i].desc")"
  log "  Verify: ${verify_desc}"
  if eval "$verify_cmd" >> "$log_file" 2>&1; then
    log "    PASS"
  else
    log "    FAIL"
    verify_failed=1
  fi
done

if [[ "$verify_failed" -eq 1 ]]; then
  log "Verification failed — not creating PR"
  git checkout main
  git branch -D "$prd_branch" 2>/dev/null || true
  set_status "failed"
  exit 1
fi

# Lint and format
log "Running lint and format..."
just lint >> "$log_file" 2>&1 || true
just format >> "$log_file" 2>&1 || true

# Commit and push
log "Committing and pushing..."
git add -A
git commit -m "feat(prd-${prd_id}): ${prd_title}" || {
  log "Nothing to commit"
  set_status "failed"
  exit 1
}
git push -u origin "$prd_branch"

# Create PR
log "Creating PR..."
pr_url="$(fj pr create --title "feat(prd-${prd_id}): ${prd_title}" --body "$(cat <<EOF
## PRD ${prd_id}: ${prd_title}

Autonomous execution of \`docs/prd/${prd_id}-*.md\`.

See log: \`logs/prd/${prd_id}-*.log\`

---
*Generated by prd-runner*
EOF
)" 2>&1)"
log "PR created: ${pr_url}"

set_status "passed"
log "PRD ${prd_id} completed successfully"
